from django.db import models

# Create your models here.
class Samples(models.Model):
    id = models.CharField(max_length=300, primary_key=True)
    name = models.CharField(max_length=300)
    stype = models.CharField(max_length=300, null=True)
    project = models.CharField(max_length=300, null=True, blank=True)
    location = models.CharField(max_length=300, null=True)
    proccessing = models.CharField(max_length=300, null=True)
    cropyear = models.CharField(max_length=300, null=True)
    varieties = models.CharField(max_length=300, null=True)
    regdate = models.CharField(max_length=300, null=True, blank=True)
    grade = models.CharField(max_length=300, null=True, blank=True)
    rating = models.CharField(max_length=300, null=True, blank=True)
    cert = models.CharField(max_length=300, null=True, blank=True)
    notes = models.TextField(max_length=300, null=True, blank=True)
    refid = models.CharField(max_length=300, null=True, blank=True)
    salenum = models.CharField(max_length=300, null=True, blank=True)
    iconum = models.CharField(max_length=300, null=True, blank=True)
    contnum = models.CharField(max_length=300, null=True, blank=True)
    tracknum = models.CharField(max_length=300, null=True, blank=True)
    country = models.CharField(max_length=300, null=True, blank=True)
    farm = models.CharField(max_length=300, null=True, blank=True)
    importer = models.CharField(max_length=300, null=True, blank=True)
    exporter = models.CharField(max_length=300, null=True, blank=True)
    wetmill = models.CharField(max_length=300, null=True, blank=True)
    drymill = models.CharField(max_length=300, null=True, blank=True)
    cooperative = models.CharField(max_length=300, null=True, blank=True)
    assosiation = models.CharField(max_length=300, null=True, blank=True)
    customer = models.CharField(max_length=300, null=True, blank=True)
    othertrac = models.TextField(max_length=300, null=True, blank=True)
    sampleweight = models.CharField(max_length=300, null=True, blank=True)
    sampleweightunit = models.CharField(max_length=300, null=True, blank=True)
    expweight = models.CharField(max_length=300, null=True, blank=True)
    expweightunit = models.CharField(max_length=300, null=True, blank=True)
    expprice = models.CharField(max_length=300, null=True, blank=True)
    exptotalprice = models.CharField(max_length=300, null=True, blank=True)
    exparrival = models.CharField(max_length=300, null=True, blank=True)
    moisture = models.CharField(max_length=300, null=True, blank=True)
    wa = models.CharField(max_length=300, null=True, blank=True)
    density = models.CharField(max_length=300, null=True, blank=True)
    physicaldefects = models.CharField(max_length=300, null=True)
    screensize = models.CharField(max_length=300, null=True, blank=True)
    classification = models.CharField(max_length=300, null=True, blank=True)
    estgreenweight = models.CharField(max_length=300, null=True, blank=True)
    sensorialdescriptors = models.TextField(max_length=300, null=True, blank=True)
    generalcomments = models.TextField(max_length=300, null=True, blank=True)
    sensorial = models.CharField(max_length=300, null=True, blank=True)
    def __str__(self):
        return self.id
#class Content(models.Model):
    #content = models.ForeignKey(Samples, on_delete=models.CASCADE)
    #text =