# Generated by Django 4.2.4 on 2023-08-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DNC', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Samples',
        ),
    ]
