# Generated by Django 4.2.4 on 2023-08-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DNC', '0002_delete_samples'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=200)),
                ('stype', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('proccessing', models.CharField(max_length=100)),
                ('cropyear', models.CharField(max_length=10)),
                ('varieties', models.CharField(max_length=100)),
                ('regdate', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('cert', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=200)),
                ('refid', models.CharField(max_length=50)),
                ('salenum', models.CharField(max_length=200)),
                ('iconum', models.CharField(max_length=200)),
                ('contnum', models.CharField(max_length=200)),
                ('tracknum', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('farm', models.CharField(max_length=200)),
                ('importer', models.CharField(max_length=200)),
                ('exporter', models.CharField(max_length=200)),
                ('wetmill', models.CharField(max_length=200)),
                ('drymill', models.CharField(max_length=200)),
                ('cooperative', models.CharField(max_length=200)),
                ('assosiation', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=200)),
                ('othertrac', models.CharField(max_length=200)),
                ('sampleweight', models.CharField(max_length=200)),
                ('sampleweightunit', models.CharField(max_length=200)),
                ('expweight', models.CharField(max_length=200)),
                ('expweightunit', models.CharField(max_length=200)),
                ('expprice', models.CharField(max_length=200)),
                ('exptotalprice', models.CharField(max_length=200)),
                ('exparrival', models.CharField(max_length=200)),
                ('moisture', models.CharField(max_length=200)),
                ('wa', models.CharField(max_length=200)),
                ('density', models.CharField(max_length=200)),
                ('physicaldefects', models.CharField(max_length=200)),
                ('screensize', models.CharField(max_length=200)),
                ('classification', models.CharField(max_length=200)),
                ('estgreenweight', models.CharField(max_length=200)),
                ('sensorialdescriptors', models.CharField(max_length=200)),
                ('generalcomments', models.CharField(max_length=200)),
                ('sensorial', models.CharField(max_length=200)),
            ],
        ),
    ]
