# Generated by Django 4.2.4 on 2023-08-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNC', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samples',
            name='regdate',
            field=models.DateTimeField(),
        ),
    ]
