# Generated by Django 4.2.4 on 2023-08-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNC', '0007_alter_samples_assosiation_alter_samples_cert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samples',
            name='regdate',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
