# Generated by Django 4.2.4 on 2023-08-28 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNC', '0009_alter_samples_assosiation_alter_samples_cert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samples',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 20, 8, 27, 923301)),
        ),
    ]
