# Generated by Django 4.2.4 on 2023-09-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNC', '0013_cuppingsci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuppingsci',
            name='Acidity_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='Flavor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='aftertaste_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='body_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='fragrance_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='freshcrop_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='off_1_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='off_2_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='off_3_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='off_4_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='off_5_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='off_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='sens_descriptors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='sweetness_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='uniform_1_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='uniform_2_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='uniform_3_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='uniform_4_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='uniform_5_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='uniformity_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
