# Generated by Django 4.2.4 on 2023-09-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNC', '0015_cuppingsci_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuppingsci',
            name='aroma_intensity_range',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuppingsci',
            name='aroma_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuppingsci',
            name='aroma_range',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
    ]
