# Generated by Django 4.2.4 on 2023-09-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNC', '0017_samples_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuppingsci',
            name='acidity_intensity_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='acidity_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='aftertaste_duration_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='aftertaste_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='aroma_intensity_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='aroma_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='body_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='body_thickness_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='ferment_level_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='flavor_intensity_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='flavor_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='fragrance_intensity_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='fragrance_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='fresh_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='fresh_woody_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='roast_level_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='sweetness_intensity_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuppingsci',
            name='sweetness_range',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
