# Generated by Django 4.2.4 on 2023-09-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNC', '0019_alter_cuppingsci_freshcrop_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuppingsci',
            name='cupdate',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
