# Generated by Django 4.2.4 on 2023-09-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNC', '0020_cuppingsci_cupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuppingsci',
            name='id',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
