# Generated by Django 4.2.4 on 2023-09-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DNC', '0024_remove_samples_shared_with_sampleshare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samples',
            name='shared_with',
        ),
    ]
