# Generated by Django 4.2.4 on 2023-09-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNC', '0028_viewperms_can_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewperms',
            name='country',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viewperms',
            name='cropyear',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viewperms',
            name='density',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viewperms',
            name='grade',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viewperms',
            name='location',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viewperms',
            name='moisture',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viewperms',
            name='name',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viewperms',
            name='physicaldefects',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viewperms',
            name='proccessing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viewperms',
            name='regdate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viewperms',
            name='screensize',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viewperms',
            name='sensorial',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viewperms',
            name='sensorialdescriptors',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viewperms',
            name='varieties',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viewperms',
            name='wa',
            field=models.BooleanField(default=True),
        ),
    ]
