# Generated by Django 4.2.4 on 2023-09-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNC', '0031_rename_sample_id_viewperms_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewperms',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
