# Generated by Django 4.2.4 on 2023-10-18 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DNC', '0032_alter_viewperms_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('stype', models.CharField(max_length=300, null=True)),
                ('project', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(max_length=300, null=True)),
                ('proccessing', models.CharField(max_length=300, null=True)),
                ('cropyear', models.CharField(max_length=300, null=True)),
                ('varieties', models.CharField(max_length=300, null=True)),
                ('regdate', models.CharField(blank=True, max_length=300, null=True)),
                ('grade', models.CharField(blank=True, max_length=300, null=True)),
                ('rating', models.CharField(blank=True, max_length=300, null=True)),
                ('cert', models.CharField(blank=True, max_length=300, null=True)),
                ('notes', models.TextField(blank=True, max_length=300, null=True)),
                ('refid', models.CharField(blank=True, max_length=300, null=True)),
                ('salenum', models.CharField(blank=True, max_length=300, null=True)),
                ('iconum', models.CharField(blank=True, max_length=300, null=True)),
                ('contnum', models.CharField(blank=True, max_length=300, null=True)),
                ('tracknum', models.CharField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=300, null=True)),
                ('farm', models.CharField(blank=True, max_length=300, null=True)),
                ('importer', models.CharField(blank=True, max_length=300, null=True)),
                ('exporter', models.CharField(blank=True, max_length=300, null=True)),
                ('wetmill', models.CharField(blank=True, max_length=300, null=True)),
                ('drymill', models.CharField(blank=True, max_length=300, null=True)),
                ('cooperative', models.CharField(blank=True, max_length=300, null=True)),
                ('assosiation', models.CharField(blank=True, max_length=300, null=True)),
                ('customer', models.CharField(blank=True, max_length=300, null=True)),
                ('othertrac', models.TextField(blank=True, max_length=300, null=True)),
                ('sampleweight', models.CharField(blank=True, max_length=300, null=True)),
                ('sampleweightunit', models.CharField(blank=True, max_length=300, null=True)),
                ('expweight', models.CharField(blank=True, max_length=300, null=True)),
                ('expweightunit', models.CharField(blank=True, max_length=300, null=True)),
                ('expprice', models.CharField(blank=True, max_length=300, null=True)),
                ('exptotalprice', models.CharField(blank=True, max_length=300, null=True)),
                ('exparrival', models.CharField(blank=True, max_length=300, null=True)),
                ('moisture', models.CharField(blank=True, max_length=300, null=True)),
                ('wa', models.CharField(blank=True, max_length=300, null=True)),
                ('density', models.CharField(blank=True, max_length=300, null=True)),
                ('physicaldefects', models.CharField(max_length=300, null=True)),
                ('screensize', models.CharField(blank=True, max_length=300, null=True)),
                ('classification', models.CharField(blank=True, max_length=300, null=True)),
                ('estgreenweight', models.CharField(blank=True, max_length=300, null=True)),
                ('sensorialdescriptors', models.TextField(blank=True, max_length=300, null=True)),
                ('generalcomments', models.TextField(blank=True, max_length=300, null=True)),
                ('sensorial', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
