# Generated by Django 4.2.4 on 2023-10-18 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DNC', '0036_rename_invetoryviewperms_inventoryviewperms'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='view_perms',
            field=models.ManyToManyField(blank=True, related_name='inventory_view_perms', through='DNC.InventoryViewPerms', to=settings.AUTH_USER_MODEL),
        ),
    ]
