# Generated by Django 4.2.4 on 2023-10-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNC', '0037_inventory_view_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sampleid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
