# Generated by Django 4.2.4 on 2023-10-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNC', '0038_inventory_code_inventory_sampleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='priceexport',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pricelocal',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
