# Generated by Django 4.2.4 on 2023-10-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNC', '0039_inventory_priceexport_inventory_pricelocal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryshare',
            old_name='sample',
            new_name='inventoryid',
        ),
        migrations.RenameField(
            model_name='inventoryviewperms',
            old_name='sample',
            new_name='inventoryid',
        ),
        migrations.AddField(
            model_name='inventory',
            name='defectq',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='g1q',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='g2q',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='g3q',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='g4q',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='g5q',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='totalq',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unsortedq',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inventoryviewperms',
            name='code',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryviewperms',
            name='defectq',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryviewperms',
            name='g1q',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryviewperms',
            name='g2q',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryviewperms',
            name='g3q',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryviewperms',
            name='g4q',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryviewperms',
            name='g5q',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryviewperms',
            name='priceexport',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryviewperms',
            name='pricelocal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryviewperms',
            name='sampleid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryviewperms',
            name='totalq',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryviewperms',
            name='unsortedq',
            field=models.BooleanField(default=True),
        ),
    ]
